# Generated by Django 4.1.3 on 2022-11-07 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_tecnologias_empresa_logo_empresa_tecnologia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='tecnologia',
            new_name='tecnologias',
        ),
    ]
